# Generated by Django 3.2 on 2022-05-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=300)),
                ('priority', models.CharField(default='Urgent, Normal, Low', max_length=300)),
                ('street_address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('supplies_needed', models.CharField(blank=True, max_length=300, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('free_field', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
