# Generated by Django 3.2 on 2022-05-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='accepted',
            new_name='aaccepted',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='city',
            new_name='acity',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='done',
            new_name='adone',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='free_field',
            new_name='afree_field',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='priority',
            new_name='apriority',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='street_address',
            new_name='astreet_address',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='supplies_needed',
            new_name='asupplies_needed',
        ),
    ]
