# Generated by Django 3.2 on 2022-05-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20220531_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='aaccepted',
            new_name='accepted',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='acity',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='adone',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='afree_field',
            new_name='free_field',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='apriority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='astreet_address',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='asupplies_needed',
            new_name='supplies_needed',
        ),
    ]
