# Generated by Django 3.2 on 2022-05-31 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220531_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='done',
        ),
        migrations.RemoveField(
            model_name='job',
            name='free_field',
        ),
        migrations.RemoveField(
            model_name='job',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='job',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='supplies_needed',
        ),
    ]
