# Generated by Django 3.2 on 2022-05-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20220531_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='priority',
            new_name='spriority',
        ),
    ]
