# Generated by Django 3.2 on 2022-05-31 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0008_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
        migrations.AddField(
            model_name='job',
            name='accepted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
